version: 2

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/vela-aws-credentials
    goarch:
      - amd64
      - arm64
universal_binaries:
  - replace: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
archives:
  -
    format_overrides:
      - goos: windows
        format: zip