name: reviewdog

on:
  pull_request:

jobs:
  diff-review:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
          check-latest: true

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yml --timeout=5m"
          fail_on_error: true
          filter_mode: diff_context
          reporter: github-pr-review

  full-review:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
          check-latest: true

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yml --timeout=5m"
          fail_on_error: false
          filter_mode: nofilter